version: "3.9"

services:
  bookstore-app:
    build: .
    container_name: bookstore-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
